### ISSUE TITLE
Issue with "Get an Access Token"

### ISSUE THREAD

**Issue by FormBurden** [ZoneMinder/mlapi#43]
I've followed your instructions up until the "Get an Access Token", and where I'm stuck is the whole example of "locahost:5000"

What do you mean by that? What should I put there? My ZoneMinder https url? or something else?

Sorry for the confusion.

**Comment by FormBurden** [comment]
Ah ok. Well, not I get a "curl: (7) Failed to connect to localhost port 5000" error. I'm guessing I should be running mlapi or something when I try to do this? But of course when I do the "python3 ./mlapi.py -c mlapiconfig.ini" command in the mlapi folder, in the ZoneMinder logs and if I run the --debug it states secret token not found MLAPI_SECRET_KEY which I assume you get from running the 'Get an Access Token" command, but that isn't working cause of connection port 5000 error.

What would I do?

**Comment by baudneo** [comment]
That's a seperate thing. The secret key it is referring to is inside mlapiconfig.ini, you can put anything you want there  it's just a "seed" to create access tokens with. You set it once and never have to worry about it again.

**Comment by baudneo** [comment]
I would focus on getting zmes setup and running first before setting mlapi up though.

**Comment by baudneo** [comment]
If you can sanitize the passwords and stuff from your config file you can post it as a github gist and then post the link here. I can look over the file and see if I can help you config it properly.

**Comment by FormBurden** [comment]
Hey, don't worry about it. I got it working correctly. When you told me about just creating your own log string of text/characters for the secret key-pass, I did just that. And everything works correctly. I really appreciate it.
