### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by goofyx** [ZoneMinder/mlapi#53]
I have that error durring mlapi service starts:
May 23 2024 15:38:41.188191 [DBG 1] HTTP error: 500 Server Error: Internal Server Error for url: http://127.0.0.1/zm/api/zones.json?token=******
Traceback (most recent call last):
  File "/var/lib/zmeventnotification/mlapi/mlapi.py", line 368, in <module>
    utils.check_and_import_zones(zmapi)
  File "/var/lib/zmeventnotification/mlapi/modules/utils.py", line 35, in check_and_import_zones
    for item in j.get('zones'):
AttributeError: 'NoneType' object has no attribute 'get'

I have one camera/monitor with 2 zones.

**Comment by connortechnology** [comment]
For some reason your api is failing.  Please check in /var/log/zm/cake*.log for further information.

**Comment by goofyx** [comment]
Thanks for fast answer, I will check it tommorow

**Comment by goofyx** [comment]
In cake*.log I had php error: "[Fatal Error: Allowed Memory Size of 134217728 Bytes Exhausted]", changed memory_limit in php.ini from 128M to 512M works.
